# 主题
theme: txd

# 语雀 API 设置
yuque:
  base: https://www.yuque.com/api/v2
  login: yinzhi
  repo: blog

# Site
title: 阿里巴巴 TXD 技术博客
subtitle: 阿里巴巴 AIS 技术体验团队博客
keywords: HTML, CSS, XML, XHTML, JavaScript, TXD
description: 阿里巴巴 | TXD | 前端 | 前端开发 | JavaScript | React | AIS | 技术体验
author: txd
language: zh-CN
timezone:

# 友情链接
links:
  -
    name: 阿里巴巴
    url: https://www.alibaba.com
  -
    name: 阿里巴巴国际UED
    url: http://www.aliued.com/
  -
    name: 阿里巴巴U一点
    url: http://www.aliued.cn/

# 导航链接
navigators:
  -
    name: HOME
    url: /
  -
    name: BLOG
    url: /blogs/
  -
    name: ABOUT
    url: /about
  -
    name: CAREERS
    url: https://txd.alibaba-inc.com/wangwang/intro/
